plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':core')
    implementation project(':infrastructure')

    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
}