plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':core')
    implementation project(':infrastructure')

    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    // MySQL / MyBatis
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.5'
    runtimeOnly 'com.mysql:mysql-connector-j'

    // Kafka
    implementation 'org.springframework.kafka:spring-kafka'

    // External API
    implementation 'org.springframework:spring-web'
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    // Testcontainers
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:mysql'

    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:mysql'

    testImplementation 'org.flywaydb:flyway-core'
    testImplementation 'org.flywaydb:flyway-mysql'
}

tasks.named('processTestResources') {
    from(project(':api').file('src/main/resources/db/migration')) {
        into 'db/migration'
    }
}