spring:
  application:
    name: mopl-api

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    validate-migration-naming: true

  jpa:
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR

server:
  port: ${API_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus