spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:mopl}
    username: ${DB_USERNAME:mopl}
    password: ${DB_PASSWORD:}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  elasticsearch:
    uris: ${ELASTICSEARCH_URL:http://localhost:9200}