spring:
  application:
    name: mopl-realtime

  jpa:
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR

server:
  port: ${REALTIME_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-seconds: ${JWT_ACCESS_EXPIRATION:1800}
  refresh-token-expiration-seconds: ${JWT_REFRESH_EXPIRATION:1209600}
